### ISSUE TITLE
Not an issue. Feed a CSV instead

### ISSUE THREAD

**Issue by worthapenny** [olivierbbb/nodesoup#1]
Hi there,

I am new here and wasn't sure how to reach out to you. I  ported your code over to python (trying Fruchterman Reingold). Now I want to try the input based on a CSV (instead of dot file). If you don't mind, could you please give me some guidance on how to proceed? Thanks. 

CSV input structure:
ID,FROM,TO
100,K,C
101,J,H
102,D,K
103,E,F
104,E,G
105,K,Z
106,D,J
107,C,X
108,B,I
109,H,C
110,I,E
111,K,B
112,J,K
113,I,C
114,H,K
115,E,A

Also what is the collection item here (g_[v_id])?
```
// line 40 of /src/fruchterman_reingold.cpp
// Attraction force between edges
        for (vertex_id_t adj_id : g_[v_id]) {
            if (adj_id > v_id) {
                continue;
            }

            Vector2D delta = positions[v_id] - positions[adj_id];
            double distance = delta.norm();
            double attraction = distance * distance / k_;

            mvmts_[v_id] -= delta / distance * attraction;
            mvmts_[adj_id] += delta / distance * attraction;
        }
```

You could send me the instruction in sample words or python or cpp, however it you feel comfortable and saves you time.

**Comment by olvb** [comment]
Hello,
`g_` refers to the memory structure holding the graph, which is an adjacency list (a very common structure for graphs, you can find more about it online).
To put it shortly, it is a list of list of neighbors (or vector of vectors in c++).
So here,`g_[v_id]` points to a list of the indices of all neighbors of vertex `v_id`.

I am not sure i understand your CSV structure. Shouldn't it be structured more like `ID, ID_FROM, ID_TO` and therefore contain rows of only one datatype (ie either numbers, or letters) ?
