### ISSUE TITLE
nodes disappear

### ISSUE THREAD

**Issue by ekg** [olivierbbb/nodesoup#2]
I'm trying to render the attached graph. After the first iteration, the nodes disappear.

[DRB1-3123.simple.dot.txt](https://github.com/olvb/nodesoup/files/2945965/DRB1-3123.simple.dot.txt)

How can I prevent this from happening?

**Comment by olvb** [comment]
Indeed there was a bug occurring when vertices shared the same coordinates. I pushed a fix, your graph should be handled properly now.
