### ISSUE TITLE
Version for dear imgui

### ISSUE THREAD

**Issue by Aarkham** [olivierbbb/nodesoup#7]
I have adapted your code to an interactive application with dear imgui.

https://github.com/Aarkham/ImNodeSoup

![ImNodeSoup](https://user-images.githubusercontent.com/8093144/232328297-a0e78c7e-d4b6-45be-b89b-9de1ea93a7fc.gif)

Hope you like it.

**Comment by olvb** [comment]
Hi, it looks pretty cool, thanks for letting me know!
